# Chapter 2 – Enterprise AI Adoption (this dataset)

# This dataset measures the percentage of enterprises with 10+ employees
# that use at least one AI technology.

# The next phase is EDA (Exploratory Data Analysis):

# 1. Where is enterprise AI adoption highest in Europe?
#    -> Which countries have the highest AI adoption percentage?

# 2. Is enterprise AI adoption increasing over time?
#    -> Compare the available Eurostat reporting years:
#       2021, 2023, 2024, and 2025.

# 3. Which countries are adopting AI fastest?
#    -> Identify the largest percentage-point increase between the
#       earliest and latest reported years.

# This dataset provides evidence for the "AI boom" part of our project.
# It does not measure energy use or environmental impact directly.

# When merged with renewable energy, electricity, emissions, and data-centre data,
# it helps answer:

# - Do high-AI-adoption countries also have more data centres?
# - Are these countries supported by cleaner electricity?
# - Is AI growth aligned with renewable energy growth?
# - Where could AI expansion create the greatest sustainability pressure?

In [1]:
import requests
import pandas as pd
from io import StringIO

# 1. Base API endpoint
url = (
    "https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/"
    "dataflow/ESTAT/ISOC_EB_AI/1.0"
)

# 2. Filters sent with the request
params = {
    "format": "csvdata",
    "formatVersion": "2.0",
    "compress": "false"

}

# 3. Send GET request
response = requests.get(url, params=params)

# 4. Check whether it worked
print(response.status_code)

# 5. Turn returned CSV text into a DataFrame
ai_adoption_df = pd.read_csv(StringIO(response.text))

# 6. Inspect the result
ai_adoption_df.head()

200

,STRUCTURE,STRUCTURE_ID,freq,size_emp,nace_r2,indic_is,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2023,5.74,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2024,5.66,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2025,5.49,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,PT,2023,13.36,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT_IUSE,ES,2023,6.88,NaN,NaN

In [2]:
ai_adoption_df

,STRUCTURE,STRUCTURE_ID,freq,size_emp,nace_r2,indic_is,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2023,5.74,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2024,5.66,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2025,5.49,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,PT,2023,13.36,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT_IUSE,ES,2023,6.88,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
72522,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SI,2023,0.00,NaN,NaN
72523,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SI,2025,0.00,NaN,NaN
72524,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SK,2023,0.18,NaN,NaN
72525,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SK,2025,1.11,NaN,NaN
72526,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,TR,2025,0.11,NaN,NaN

In [3]:
ai_adoption_df_clean=ai_adoption_df.copy()

In [4]:
ai_adoption_df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'freq', 'size_emp', 'nace_r2', 'indic_is',
       'unit', 'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='object')

In [5]:
ai_adoption_df.shape

(72527, 12)

In [6]:
ai_adoption_df_clean.columns = (
    ai_adoption_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [7]:
ai_adoption_df_clean.columns

Index(['structure', 'structure_id', 'freq', 'size_emp', 'nace_r2', 'indic_is',
       'unit', 'geo', 'time_period', 'obs_value', 'obs_flag', 'conf_status'],
      dtype='object')

In [8]:
ai_adoption_df_clean_dropped = ai_adoption_df_clean.drop(
    columns=["structure", "structure_id"]
)

In [9]:
columns_to_check = [
    "freq",
    "size_emp",
    "nace_r2",
    "indic_is",
    "unit"
]

for column in columns_to_check:
    print(f"\n--- {column} ---")
    print(ai_adoption_df_clean_dropped[column].value_counts())

--- freq ---
freq
A    72527
Name: count, dtype: int64

--- size_emp ---
size_emp
10-249    13988
50-249    13988
GE10      13988
GE250     13987
10-49     13979
2-9        1286
0-9         912
0_1         399
Name: count, dtype: int64

--- nace_r2 ---
nace_r2
C10-S951_X_K    72527
Name: count, dtype: int64

--- indic_is ---
indic_is
E_AI_PITS          2146
E_AI_PPP           2146
E_AI_PMS           2146
E_AI_PLOG          2146
E_AI_BDDT          1983
                   ...
E_AI_BIAS_ARDY      212
E_AI_BIAS_AMOWN     209
E_AI_BIAS_AOS       209
E_AI_BIAS_ADOWN     209
E_AI_PDI            142
Name: count, Length: 63, dtype: int64

--- unit ---
unit
PC_ENT            28062
PC_ENT_IUSE       26185
PC_ENT_AI_TANY     9464
PC_ENT_AI_TX       4454
PC_ENT_AI_EC       3945
PC_ENT_AI_PDI       417
Name: count, dtype: int64

In [10]:
ai_adoption_df_clean_dropped[
    ai_adoption_df_clean_dropped["indic_is"] == "E_AI_TANY"
][["size_emp", "unit"]].value_counts()

size_emp  unit
10-49     PC_ENT_IUSE    140
          PC_ENT         140
10-249    PC_ENT_IUSE    140
          PC_ENT         140
GE10      PC_ENT         140
          PC_ENT_IUSE    140
50-249    PC_ENT         140
          PC_ENT_IUSE    140
GE250     PC_ENT         140
          PC_ENT_IUSE    140
2-9       PC_ENT          12
          PC_ENT_IUSE     12
0-9       PC_ENT           9
          PC_ENT_IUSE      9
0_1       PC_ENT           5
          PC_ENT_IUSE      5
Name: count, dtype: int64

In [11]:
ai_adoption_project = ai_adoption_df_clean_dropped[
    (ai_adoption_df_clean_dropped["size_emp"] == "GE10")
    & (ai_adoption_df_clean_dropped["indic_is"] == "E_AI_TANY")
    & (ai_adoption_df_clean_dropped["unit"] == "PC_ENT")
].copy()

In [12]:
ai_adoption_final = ai_adoption_project[
    ["geo", "time_period", "obs_value"]
].rename(
    columns={
        "geo": "country_code",
        "time_period": "year",
        "obs_value": "ai_adoption_pct"
    }
)

In [13]:
ai_adoption_final

      country_code  year  ai_adoption_pct
55148           AL  2021             3.67
55149           AL  2024             8.91
55150           AL  2025             8.99
55151           AT  2021             8.83
55152           AT  2023            10.79
...            ...   ...              ...
55283           SK  2025            18.00
55284           TR  2021             2.69
55285           TR  2023             5.51
55286           TR  2024             4.42
55287           TR  2025             7.41

[140 rows x 3 columns]

In [14]:
ai_adoption_final.groupby("country_code")["ai_adoption_pct"].mean()

country_code
AL            7.1900
AT           17.4600
BA            6.1375
BE           20.8450
BG            5.4825
CY            6.1075
CZ            9.8050
DE           16.9575
DK           27.1675
EA           13.2400
EE           11.3125
EL            6.3325
ES           12.1075
EU27_2020    12.2850
FI           23.2700
FR           10.1550
HR           10.8950
HU            6.1100
IE           12.6075
IT            8.9550
LT            9.8425
LU           21.1975
LV            7.3225
ME            6.7275
MK               NaN
MT           15.5350
NL           20.8675
NO           17.4125
PL            5.1975
PT            8.8075
RO            2.7925
RS            4.9475
SE           20.1050
SI           16.4000
SK           10.2525
TR            5.0075
Name: ai_adoption_pct, dtype: float64

In [15]:
ai_adoption_by_year = (
    ai_adoption_final
    .groupby(["country_code", "year"])["ai_adoption_pct"]
    .mean()
    .reset_index()
)

In [16]:
exclude_codes = ["EA", "EU27_2020"]

ai_adoption_countries = ai_adoption_final[
    ~ai_adoption_final["country_code"].isin(exclude_codes)
].copy()

In [17]:
ai_adoption_by_year["country_code"].unique()

array(['AL', 'AT', 'BA', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EA', 'EE',
       'EL', 'ES', 'EU27_2020', 'FI', 'FR', 'HR', 'HU', 'IE', 'IT', 'LT',
       'LU', 'LV', 'ME', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS',
       'SE', 'SI', 'SK', 'TR'], dtype=object)

In [18]:
ai_2024 = ai_adoption_countries[
    ai_adoption_countries["year"] == 2024
].sort_values("ai_adoption_pct", ascending=False)

In [19]:
country_names = {
    "AL": "Albania",
    "AT": "Austria",
    "BA": "Bosnia and Herzegovina",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DK": "Denmark",
    "EE": "Estonia",
    "EL": "Greece",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "HR": "Croatia",
    "HU": "Hungary",
    "IE": "Ireland",
    "IT": "Italy",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "ME": "Montenegro",
    "MK": "North Macedonia",
    "MT": "Malta",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RS": "Serbia",
    "SE": "Sweden",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "TR": "Türkiye"
}

In [20]:

plt.figure(figsize=(10, 8))

plt.barh(
    ai_2024["country_code"],
    ai_2024["ai_adoption_pct"]
)

plt.xlabel("Enterprises using at least one AI technology (%)")
plt.ylabel("Country")
plt.title("Enterprise AI Adoption in Europe, 2024")

plt.gca().invert_yaxis()
plt.show()

NameError: name 'plt' is not defined

In [ ]:
ai_adoption_by_year["year"].value_counts()

year
2021    36
2024    35
2025    35
2023    34
Name: count, dtype: int64

In [ ]:
ai_adoption_project

,freq,size_emp,nace_r2,indic_is,unit,geo,time_period,obs_value,obs_flag,conf_status
55148,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AL,2021,3.67,NaN,NaN
55149,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AL,2024,8.91,NaN,NaN
55150,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AL,2025,8.99,NaN,NaN
55151,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AT,2021,8.83,NaN,NaN
55152,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AT,2023,10.79,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
55283,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,SK,2025,18.00,NaN,NaN
55284,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2021,2.69,NaN,NaN
55285,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2023,5.51,NaN,NaN
55286,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2024,4.42,NaN,NaN
55287,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2025,7.41,NaN,NaN

In [ ]:
ai_adoption_final["ai_adoption_pct"].isnull().sum()

np.int64(1)

In [ ]:
ai_adoption_final = ai_adoption_final.dropna(
    subset=["ai_adoption_pct"])

In [ ]:
ai_adoption_final

      country_code  year  ai_adoption_pct
55148           AL  2021             3.67
55149           AL  2024             8.91
55150           AL  2025             8.99
55151           AT  2021             8.83
55152           AT  2023            10.79
...            ...   ...              ...
55283           SK  2025            18.00
55284           TR  2021             2.69
55285           TR  2023             5.51
55286           TR  2024             4.42
55287           TR  2025             7.41

[140 rows x 3 columns]

In [ ]:
ai_adoption_final.head()

      country_code  year  ai_adoption_pct
55148           AL  2021             3.67
55149           AL  2024             8.91
55150           AL  2025             8.99
55151           AT  2021             8.83
55152           AT  2023            10.79

In [21]:
ai_adoption_df_clean

,structure,structure_id,freq,size_emp,nace_r2,indic_is,unit,geo,time_period,obs_value,obs_flag,conf_status
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2023,5.74,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2024,5.66,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2025,5.49,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,PT,2023,13.36,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT_IUSE,ES,2023,6.88,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
72522,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SI,2023,0.00,NaN,NaN
72523,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SI,2025,0.00,NaN,NaN
72524,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SK,2023,0.18,NaN,NaN
72525,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SK,2025,1.11,NaN,NaN
72526,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,TR,2025,0.11,NaN,NaN

In [22]:
ai_adoption_df_clean.columns

Index(['structure', 'structure_id', 'freq', 'size_emp', 'nace_r2', 'indic_is',
       'unit', 'geo', 'time_period', 'obs_value', 'obs_flag', 'conf_status'],
      dtype='object')

In [23]:
ai_adoption_df_clean = ai_adoption_df_clean.drop(
    columns=["structure", "structure_id"]
)

In [24]:
ai_adoption_df_clean = ai_adoption_df_clean[
    (ai_adoption_df_clean["freq"] == "A")
    & (ai_adoption_df_clean["size_emp"] == "GE10")
    & (ai_adoption_df_clean["nace_r2"] == "C10-S951_X_K")
    & (ai_adoption_df_clean["indic_is"] == "E_AI_TANY")
    & (ai_adoption_df_clean["unit"] == "PC_ENT")]

In [25]:
ai_adoption_df_clean["time_period"]

55148    2021
55149    2024
55150    2025
55151    2021
55152    2023
         ...
55283    2025
55284    2021
55285    2023
55286    2024
55287    2025
Name: time_period, Length: 140, dtype: int64

In [26]:
ai_adoption_df_clean = ai_adoption_df_clean.rename(
    columns={
        "geo": "country_code",
        "time_period": "year",
        "obs_value": "ai_adoption_pct"
    }
)

In [27]:
ai_adoption_df_clean["year"] = pd.to_numeric(
    ai_adoption_df_clean["year"],
    errors="coerce"
)

ai_adoption_df_clean["ai_adoption_pct"] = pd.to_numeric(
    ai_adoption_df_clean["ai_adoption_pct"],
    errors="coerce"
)

In [28]:
ai_adoption_df_clean = ai_adoption_df_clean.dropna(
    subset=["ai_adoption_pct"]
)

In [31]:
ai_adoption_df_clean = ai_adoption_df_clean.drop(
    columns=["obs_flag", "conf_status"]
)

In [32]:
ai_adoption_df_clean = ai_adoption_df_clean.reset_index(drop=True)

In [34]:
ai_adoption_df_clean

,freq,size_emp,nace_r2,indic_is,unit,country_code,year,ai_adoption_pct
0,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AL,2021,3.67
1,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AL,2024,8.91
2,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AL,2025,8.99
3,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AT,2021,8.83
4,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,AT,2023,10.79
...,...,...,...,...,...,...,...,...
126,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,SK,2025,18.00
127,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2021,2.69
128,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2023,5.51
129,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2024,4.42
130,A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,TR,2025,7.41

In [35]:
ai_adoption_df_clean.to_csv(
    "ai_adoption_cleaned.csv",
    index=False
)

## Cleaned AI Adoption Dataset

This dataset was collected from the Eurostat API and measures the percentage of enterprises with 10+ employees using at least one AI technology.

Cleaning steps:

* Filtered to annual observations (`freq = A`)
* Kept enterprises with 10+ employees (`size_emp = GE10`)
* Kept the “uses at least one AI technology” indicator (`E_AI_TANY`)
* Kept percentage of enterprises (`PC_ENT`)
* Removed technical metadata, regional aggregates, and rows with missing values
* Confirmed one observation per country-year

Final columns:

* `geo`: country code
* `time_period`: reporting year
* `obs_value`: AI adoption percentage

# The next phase is EDA (Exploratory Data Analysis):

# 1. Where is enterprise AI adoption highest in Europe?

# -> Which countries have the highest percentage of enterprises

# using at least one AI technology?

# 2. Is enterprise AI adoption increasing over time?

# -> How has AI adoption changed across the available reporting years:

# 2021, 2023, 2024, and 2025?

# 3. Which countries are adopting AI fastest?

# -> Which countries show the largest percentage-point increase

# between their earliest and latest available observation?

# These questions help establish the demand-side evidence for Europe's AI boom.

# This dataset does not measure electricity use, emissions, or environmental impact directly.

# Then, when merged with our renewable energy, electricity,

# emissions, and data-centre datasets, we can answer:

# - Do countries with high AI adoption also have a larger data-centre presence?

# - Are high-AI-adoption countries supported by more renewable electricity?

# - Is AI adoption growing in countries with cleaner electricity systems?

# - Where could growing AI demand create the greatest sustainability pressure?

# Think of the project like a story:

# Chapter 1 – Renewable energy

# Is Europe's electricity system becoming cleaner?

# Chapter 2 – Enterprise AI adoption (this dataset)

# Where is business AI use highest and growing fastest?

# Chapter 3 – Data-centre infrastructure

# Where is the physical infrastructure supporting AI concentrated?

# Chapter 4 – Merge

# Does AI growth align with cleaner electricity,

# or could it increase pressure on fossil-fuel-dependent grids?

# This final comparison helps answer:

# "Is Europe's AI boom environmentally sustainable?"