In [1]:
import requests
import pandas as pd
from io import StringIO

# 1. Base API endpoint
url = (
    "https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/"
    "dataflow/ESTAT/ISOC_EB_AI/1.0"
)

# 2. Filters sent with the request
params = {
    "format": "csvdata",
    "formatVersion": "2.0",
    "compress": "false"

}

# 3. Send GET request
response = requests.get(url, params=params)

# 4. Check whether it worked
print(response.status_code)

# 5. Turn returned CSV text into a DataFrame
ai_adoption_df = pd.read_csv(StringIO(response.text))

# 6. Inspect the result
ai_adoption_df.head()

200

,STRUCTURE,STRUCTURE_ID,freq,size_emp,nace_r2,indic_is,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2023,5.74,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2024,5.66,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2025,5.49,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,PT,2023,13.36,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT_IUSE,ES,2023,6.88,NaN,NaN

In [2]:
ai_adoption_df

,STRUCTURE,STRUCTURE_ID,freq,size_emp,nace_r2,indic_is,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2023,5.74,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2024,5.66,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,ES,2025,5.49,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT,PT,2023,13.36,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,0-9,C10-S951_X_K,E_AIX_CC1SIX_DA,PC_ENT_IUSE,ES,2023,6.88,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
72522,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SI,2023,0.00,NaN,NaN
72523,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SI,2025,0.00,NaN,NaN
72524,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SK,2023,0.18,NaN,NaN
72525,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,SK,2025,1.11,NaN,NaN
72526,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE250,C10-S951_X_K,E_DI3_VLO_AI_TANY,PC_ENT,TR,2025,0.11,NaN,NaN

In [3]:
ai_adoption_df_clean=ai_adoption_df.copy()

In [4]:
ai_adoption_df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'freq', 'size_emp', 'nace_r2', 'indic_is',
       'unit', 'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='object')

In [5]:
ai_adoption_df.shape

(72527, 12)

In [6]:
ai_adoption_df_clean.columns = (
    ai_adoption_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [9]:
ai_adoption_df_clean["structure"].unique()

array(['dataflow'], dtype=object)