In [1]:
import requests
import pandas as pd
from io import StringIO

# 1. Base API endpoint
url = (
    "https://ec.europa.eu/eurostat/api/dissemination/sdmx/3.0/data/"
    "dataflow/ESTAT/ISOC_EB_AI/1.0"
)

# 2. Filters sent with the request
params = {
    "format": "csvdata",
    "formatVersion": "2.0",
    "compress": "false",
    "c[freq]": "A",
    "c[size_emp]": "GE10",
    "c[nace_r2]": "C10-S951_X_K",
    "c[indic_is]": "E_AI_TANY",
    "c[unit]": "PC_ENT",
    "c[geo]": "NL,DE,FR,IE,SE",
    "c[TIME_PERIOD]": "ge:2021"
}

# 3. Send GET request
response = requests.get(url, params=params)

# 4. Check whether it worked
print(response.status_code)

# 5. Turn returned CSV text into a DataFrame
ai_adoption_df = pd.read_csv(StringIO(response.text))

# 6. Inspect the result
ai_adoption_df.head()

200

,STRUCTURE,STRUCTURE_ID,freq,size_emp,nace_r2,indic_is,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2021,10.56,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2023,11.55,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2024,19.75,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2025,25.97,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,FR,2021,6.67,NaN,NaN

In [2]:
ai_adoption_df

,STRUCTURE,STRUCTURE_ID,freq,size_emp,nace_r2,indic_is,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2021,10.56,NaN,NaN
1,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2023,11.55,NaN,NaN
2,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2024,19.75,NaN,NaN
3,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,DE,2025,25.97,NaN,NaN
4,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,FR,2021,6.67,NaN,NaN
5,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,FR,2023,5.88,b,NaN
6,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,FR,2024,9.91,NaN,NaN
7,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,FR,2025,18.16,NaN,NaN
8,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,IE,2021,7.88,NaN,NaN
9,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,IE,2023,8.01,NaN,NaN
10,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,IE,2024,14.90,NaN,NaN
11,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,IE,2025,19.64,NaN,NaN
12,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,NL,2021,13.10,NaN,NaN
13,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,NL,2023,14.10,NaN,NaN
14,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,NL,2024,23.06,NaN,NaN
15,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,NL,2025,33.21,b,NaN
16,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,SE,2021,9.92,NaN,NaN
17,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,SE,2023,10.37,b,NaN
18,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,SE,2024,25.09,NaN,NaN
19,dataflow,ESTAT:ISOC_EB_AI(1.0),A,GE10,C10-S951_X_K,E_AI_TANY,PC_ENT,SE,2025,35.04,NaN,NaN

In [ ]:
ai_adoption_df.

Index(['STRUCTURE', 'STRUCTURE_ID', 'freq', 'size_emp', 'nace_r2', 'indic_is',
       'unit', 'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='object')

In [5]:
ai_adoption_df.shape

(20, 12)