In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/Orgo4ever/data-wrangling-project/main/Data/Raw%20data/eurostat_renewable_energy_share.csv"

df = pd.read_csv(url)

df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,nrg_bal,Energy balance,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:NRG_IND_REN$DEFAULTVIEW(1.0),Share of energy from renewable sources,A,Annual,REN,Renewable energy - overall,PC,Percentage,AL,Albania,2015,NaN,34.913,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:NRG_IND_REN$DEFAULTVIEW(1.0),Share of energy from renewable sources,A,Annual,REN,Renewable energy - overall,PC,Percentage,AL,Albania,2016,NaN,36.953,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:NRG_IND_REN$DEFAULTVIEW(1.0),Share of energy from renewable sources,A,Annual,REN,Renewable energy - overall,PC,Percentage,AL,Albania,2017,NaN,35.776,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:NRG_IND_REN$DEFAULTVIEW(1.0),Share of energy from renewable sources,A,Annual,REN,Renewable energy - overall,PC,Percentage,AL,Albania,2018,NaN,36.572,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:NRG_IND_REN$DEFAULTVIEW(1.0),Share of energy from renewable sources,A,Annual,REN,Renewable energy - overall,PC,Percentage,AL,Albania,2019,NaN,38.042,NaN,NaN,NaN,NaN,NaN

In [4]:
df.isnull()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,nrg_bal,Energy balance,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
378,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
379,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
380,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True
381,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True

In [5]:
df.isnull().sum() / len(df) * 100

STRUCTURE                                   0.0
STRUCTURE_ID                                0.0
STRUCTURE_NAME                              0.0
freq                                        0.0
Time frequency                              0.0
nrg_bal                                     0.0
Energy balance                              0.0
unit                                        0.0
Unit of measure                             0.0
geo                                         0.0
Geopolitical entity (reporting)             0.0
TIME_PERIOD                                 0.0
Time                                      100.0
OBS_VALUE                                   0.0
Observation value                         100.0
OBS_FLAG                                  100.0
Observation status (Flag) V2 structure    100.0
CONF_STATUS                               100.0
Confidentiality status (flag)             100.0
dtype: float64

In [6]:
df.isna().sum()

STRUCTURE                                   0
STRUCTURE_ID                                0
STRUCTURE_NAME                              0
freq                                        0
Time frequency                              0
nrg_bal                                     0
Energy balance                              0
unit                                        0
Unit of measure                             0
geo                                         0
Geopolitical entity (reporting)             0
TIME_PERIOD                                 0
Time                                      382
OBS_VALUE                                   0
Observation value                         382
OBS_FLAG                                  382
Observation status (Flag) V2 structure    382
CONF_STATUS                               382
Confidentiality status (flag)             382
dtype: int64

In [10]:
df = df.dropna(axis=1, how="all")

In [12]:
df.shape

(382, 13)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 382 entries, 0 to 381
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   STRUCTURE                        382 non-null    str
 1   STRUCTURE_ID                     382 non-null    str
 2   STRUCTURE_NAME                   382 non-null    str
 3   freq                             382 non-null    str
 4   Time frequency                   382 non-null    str
 5   nrg_bal                          382 non-null    str
 6   Energy balance                   382 non-null    str
 7   unit                             382 non-null    str
 8   Unit of measure                  382 non-null    str
 9   geo                              382 non-null    str
 10  Geopolitical entity (reporting)  382 non-null    str
 11  TIME_PERIOD                      382 non-null    int64
 12  OBS_VALUE                        382 non-null    float64
dtypes: float64(1), int64(1), str(11)
memory usage: 38.9 KB

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.nunique()

STRUCTURE                            1
STRUCTURE_ID                         1
STRUCTURE_NAME                       1
freq                                 1
Time frequency                       1
nrg_bal                              1
Energy balance                       1
unit                                 1
Unit of measure                      1
geo                                 40
Geopolitical entity (reporting)     40
TIME_PERIOD                         10
OBS_VALUE                          377
dtype: int64

In [16]:
df = df.drop(columns=[
    "STRUCTURE",
    "STRUCTURE_ID",
    "STRUCTURE_NAME",
    "freq",
    "Time frequency",
    "nrg_bal",
    "Energy balance",
    "unit",
    "Unit of measure"
])

In [17]:
df = df.rename(columns={
    "Geopolitical entity (reporting)": "country",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "renewable_energy_share"
})

In [18]:
df.head()

  geo  country  year  renewable_energy_share
0  AL  Albania  2015                  34.913
1  AL  Albania  2016                  36.953
2  AL  Albania  2017                  35.776
3  AL  Albania  2018                  36.572
4  AL  Albania  2019                  38.042

In [19]:
df.head(10)

  geo  country  year  renewable_energy_share
0  AL  Albania  2015                  34.913
1  AL  Albania  2016                  36.953
2  AL  Albania  2017                  35.776
3  AL  Albania  2018                  36.572
4  AL  Albania  2019                  38.042
5  AL  Albania  2020                  45.015
6  AL  Albania  2021                  41.389
7  AL  Albania  2022                  44.076
8  AL  Albania  2023                  46.620
9  AL  Albania  2024                  43.111

In [20]:
df.tail()

    geo  country  year  renewable_energy_share
377  XK  Kosovo*  2020                  24.401
378  XK  Kosovo*  2021                  22.061
379  XK  Kosovo*  2022                  18.773
380  XK  Kosovo*  2023                  20.215
381  XK  Kosovo*  2024                  18.020

In [21]:
df

    geo  country  year  renewable_energy_share
0    AL  Albania  2015                  34.913
1    AL  Albania  2016                  36.953
2    AL  Albania  2017                  35.776
3    AL  Albania  2018                  36.572
4    AL  Albania  2019                  38.042
..   ..      ...   ...                     ...
377  XK  Kosovo*  2020                  24.401
378  XK  Kosovo*  2021                  22.061
379  XK  Kosovo*  2022                  18.773
380  XK  Kosovo*  2023                  20.215
381  XK  Kosovo*  2024                  18.020

[382 rows x 4 columns]

In [22]:
df.to_csv("cleaned_renewable_energy.csv", index=False)

In [23]:
df = df.rename(columns={"geo": "country_code"})

In [24]:
df = df.sort_values(["country", "year"])

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 382 entries, 0 to 351
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country_code            382 non-null    str
 1   country                 382 non-null    str
 2   year                    382 non-null    int64
 3   renewable_energy_share  382 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 14.9 KB

In [26]:
df = df.reset_index(drop=True)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 382 entries, 0 to 381
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country_code            382 non-null    str
 1   country                 382 non-null    str
 2   year                    382 non-null    int64
 3   renewable_energy_share  382 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 12.1 KB

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df["country"].unique()

<StringArray>
[                                  'Albania',
                                   'Austria',
                                   'Belgium',
                    'Bosnia and Herzegovina',
                                  'Bulgaria',
                                   'Croatia',
                                    'Cyprus',
                                   'Czechia',
                                   'Denmark',
                                   'Estonia',
      'Euro area – 20 countries (2023-2025)',
      'Euro area – 21 countries (from 2026)',
 'European Union - 27 countries (from 2020)',
                                   'Finland',
                                    'France',
                                   'Georgia',
                                   'Germany',
                                    'Greece',
                                   'Hungary',
                                   'Iceland',
                                   'Ireland',
                                     'Italy',
                                   'Kosovo*',
                                    'Latvia',
                                 'Lithuania',
                                'Luxembourg',
                                     'Malta',
                                   'Moldova',
                                'Montenegro',
                               'Netherlands',
                           'North Macedonia',
                                    'Norway',
                                    'Poland',
                                  'Portugal',
                                   'Romania',
                                    'Serbia',
                                  'Slovakia',
                                  'Slovenia',
                                     'Spain',
                                    'Sweden']
Length: 40, dtype: str

In [31]:
df["year"].unique()

array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [32]:
df["renewable_energy_share"].describe()

count    382.000000
mean      27.420469
std       16.146516
min        4.987000
25%       17.132000
50%       22.572500
75%       35.093750
max       83.725000
Name: renewable_energy_share, dtype: float64

In [ ]:
#The next phase is EDA (Exploratory Data Analysis):

#1.How renewable is Europe's electricity? -> Which countries have the highest renewable energy share?
#2.Is Europe becoming greener over time? -> How has renewable energy share changed over time?
#3. Which countries are improving the fastest? -> hich countries have seen the biggest increase?
#These are all useful because they establish whether Europe's energy system is becoming cleaner—the context needed before talking about AI

In [ ]:
#Then, when you merge with your AI dataset, you answer the real question:
    #·Where are AI data centers located?
    #·Do those countries rely on renewable energy?
    #·Is AI expanding in countries with cleaner electricity?
    #·Is renewable energy growing fast enough to support AI's increasing electricity demand?

In [ ]:
#Think of your project like a story

#Chapter 1 – Renewable energy (this dataset)

    #Is Europe getting greener?

#Chapter 2 – AI infrastructure

    #Where is AI growing?

#Chapter 3 – Merge

    #Does AI growth align with clean energy, or is it increasing pressure on fossil-fuel-based electricity?

#That third chapter is where you answer "Is Europe's AI boom environmentally sustainable?" 
#The first two chapters provide the evidence needed to reach that conclusion.